# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170527_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
    ]
